name: Projects healthcheck

on: workflow_dispatch
  # schedule:
  #   - cron: '0 0/4 * * *'

env:
 SUBQUERY_TOKEN: ${{ secrets.SUBQUERY_TOKEN }}

jobs:
  generate_project_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      - name: Generate table
        run: python ./tests/utils/generate_network_status.py

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: gh-pages
