name: Manual deploy to staging

on:
  workflow_dispatch:
    inputs:
      networks:
        description: 'Which networks will deploy?'
        required: true
        type: string
      batch_size:
        description: 'Set batch size [Documentation](https://doc.subquery.network/academy/tutorials_examples/batch-size.html#why-change-the-batch-size)'
        required: true
        default: "15"
      indexer_image_version:
        description: 'Version of docker image for indexer'
        required: true
        default: v0.33.0
      query_image_version:
        description: 'Version of docker image for query'
        required: true
        default: v0.14.1
      subquery_cli_version:
        description: '[CLI](https://github.com/fewensa/subquery-cli/releases) version'
        required: true
        default: 0.2.6
      reindex:
        description: 'Re-index these networks? ⚠️Attention this will clear all data on stage env⚠️'
        required: true
        type: boolean
        default: false

env:
  SUBQUERY_ORG: nova-wallet

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        list_elements=(${{ github.event.inputs.networks }})
        JSON="{\"include\":["

        for item in ${list_elements[*]}
        do
            JSONline="{\"chain\": \"$item\"},"

            if [[ "$JSON" != *"$JSONline"* ]]; then
                JSON="$JSON$JSONline"
            fi
            echo $item
        done <<< "$DIFF"

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo $JSON

        echo "::set-output name=matrix::$( echo "$JSON" )"


  deploy-subquery:
    needs: setup
    name: Deploy subquery
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/fewensa/subquery-cli/releases/download/v${{ github.event.inputs.subquery_cli_version }}/subquery-linux-x86_64.zip
          unzip subquery-linux-x86_64.zip -d $HOME/.local/bin/
          rm -rf subquery-linux-x86_64.zip
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Deploy
        if: ${{ github.event.inputs.reindex == 'false' }}
        run: |
          subquery --token ${{ secrets.SUBQUERY_TOKEN }} deployment deploy \
            --org ${{ env.SUBQUERY_ORG }} \
            --key nova-wallet-${{ matrix.chain }} \
            --branch deploy \
            --sub-folder ./networks/${{ matrix.chain }} \
            --type stage \
            --indexer-image-version ${{ github.event.inputs.indexer_image_version }} \
            --query-image-version ${{ github.event.inputs.query_image_version }} \
            --batch-size ${{ github.event.inputs.batch_size }}

      - name: Redeploy
        if: ${{ github.event.inputs.reindex == 'true' }}
        run: |
          subquery --token ${{ secrets.SUBQUERY_TOKEN }} deployment deploy \
            --org ${{ env.SUBQUERY_ORG }} \
            --key nova-wallet-${{ matrix.chain }} \
            --branch deploy \
            --sub-folder ./networks/${{ matrix.chain }} \
            --type stage \
            --indexer-image-version ${{ github.event.inputs.indexer_image_version }} \
            --query-image-version ${{ github.event.inputs.query_image_version }} \
            --batch-size ${{ github.event.inputs.batch_size }} \
            --force
