name: Promote staging to production

on:
  workflow_dispatch:
    inputs:
      networks:
        description: 'Which networks will promote?'
        required: true
        type: string
      subquery_cli_version:
        description: '[CLI](https://github.com/fewensa/subquery-cli/releases) version'
        required: true
        default: 0.2.5

env:
  SUBQUERY_ORG: nova-wallet
  SUBQUERY_TOKEN: ${{ secrets.SUBQUERY_TOKEN }}


jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        list_elements=(${{ github.event.inputs.networks }})
        JSON="{\"include\":["

        for item in ${list_elements[*]}
        do
            JSONline="{\"chain\": \"$item\"},"

            if [[ "$JSON" != *"$JSONline"* ]]; then
                JSON="$JSON$JSONline"
            fi
            echo $item
        done <<< "$DIFF"

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo $JSON

        echo "::set-output name=matrix::$( echo "$JSON" )"

  deploy-subquery:
    needs: setup
    name: Deploy subquery
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    env:
      PROJECT_KEY: nova-wallet-${{ matrix.chain }}

    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      - name: Check current stage status
        run: python -m pytest ./tests/test_projects.py

      - name: Install dependencies for promote
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/fewensa/subquery-cli/releases/download/v${{ github.event.inputs.subquery_cli_version }}/subquery-linux-x86_64.zip
          unzip subquery-linux-x86_64.zip -d $HOME/.local/bin/
          rm -rf subquery-linux-x86_64.zip
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Promote to production
        run: |
          subquery --token ${{ secrets.SUBQUERY_TOKEN }} deployment promote \
            --org ${{ env.SUBQUERY_ORG }} \
            --key nova-wallet-${{ matrix.chain }}
